project_name: cli

before:
  hooks:
    - make mock
    - go mod tidy
    - go generate ./...

builds:
  - id: "zeabur"
    main: ./cmd
    binary: "zeabur"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: "zeabur_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    id: "binary"
    # to archive as zip on Windows.
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^test:"
      - "^Merge pull request"

release:
  extra_files:
    - glob: "README.md"

brews:
  - repository:
      owner: zeabur
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://zeabur.com"
    description: "Zeabur's official command line tool"

scoop:
  url_template: "https://github.com/zeabur/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: zeabur
    name: cli
  homepage: "https://zeabur.com"
  description: "Zeabur's official command line tool"
  repository:
    pull_request:
      enabled: true
      draft: false
